config/routes.rb
Events::Application.routes.draw do

  resources :user_sessions

  resources :users do
    member do
      get :following, :followers
    end
  end

  get "users/new"

  resources :users

  resources :events
  resources :relationships
  
  match '/signup',  :to => 'users#new'
  match '/login',  :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  match '/following', :to => 'users#following'
  
  match '/create',  :to => 'events#new'
  match '/allevents',   :to => 'events#index'
      
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/tasks', :to => 'users#task'
  
  root :to => "pages#home"

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  
  has_many :events, :dependent => :destroy
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
                           
  has_many :following, :through => :relationships, :source => :followed

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username,  :presence   => true,
                        :length     => { :maximum => 20 }
                        :uniqueness 
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 4..40}

  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end 
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end

  def tasked?(followed)
    relationships.find_by_followed_id(followed)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UserSessionsHelper
  
  def new
    @user = User.new
    @title = "Sign up"
    
    respond_to do |format|
      format.html
      format.json { render :json => @user }
    end
  end
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
    
    respond_to do |format|
      format.html
      format.json { render :json => @users}
    end
  end
  
  def show
    @user = current_user
    @events = @user.events.paginate(:page => params[:page])
    @title = @user.username
    
    respond_to do |format|
      format.html
      format.json { render :json => @user}
    end
  end
  
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'Registration was successful!.') }
        format.json  { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new"}
        format.json { render :json => @user.errors, :status => :unprocessable_entity}
      end
    end
  end
  
  def edit
    @title = "Edit user"
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => "Profile updated.") }
        format.json { head :ok}
      else
        format.html { render :action => "edit" }
        @title = "Edit user"
        format.json  { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy 
    User.find(params[:id]).destroy
    
    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
      format.json { head :ok }
    end
  end
  
  def following
    @title = "Following"
    @user  = current_user
    @users = @user.following.paginate(:page => params[:page])
    
    respond_to do |format|
      format.html { render :action => 'show_follow'}
      format.json { render :json => @users }
    end
  end
  
  def task
    @title = "Tasks"
    @user  = current_user
    @event = Event.find(params[:id])
    @relationship = Relationship.find_by_follower_id_and_followed_id(@user.id, params[:id])
    @location = [@event.street, @event.city,@event.state, @event.zip]
    @location = @location.join(',')
    @address = Geokit::Geocoders::GoogleGeocoder.geocode @location
    @b = @relationship.latitude && @relationship.longitude
        
    respond_to do |format|
      format.html { render :action => 'task'}
      format.json { render :json => @address }
    end
  end
  
  private

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.username,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/users/_form.html.erb
<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
	<table class="users" summary="Users">
			<td class="event">
  			<%= gravatar_for user, :size => 30 %>
  			<%= link_to user.username, user %>
			</td>
	</table>
</tr>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(current_user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for current_user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
		<%= link_to "New event?", create_path, :class => "newevent_button round" %>
      </h1>
	  <% unless @user.events.empty? %>
		<table class="events" summary="User events">
			<%= render @events %>
		</table>
		<%= will_paginate @events%>
	  <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.username %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
	  <strong>Events</strong> <%= @user.events.count %>
	  <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>
      
      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>

    <td class="sidebar round">
      <strong>Name</strong> <%= @user.username %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Events</strong> <%= @user.events.count %>
      <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/users/task.html.erb
<h1><%= Event %></h1>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>
<p>
  <b>Description:</b>
  <%= @event.description %>
</p>
<p>
  <b>Address:</b>
  <%= @event.street %>
  <%= @event.city %>
  <%= @event.state %>
</p>
<p>
	<b>Target Lat/Long</b>
	<%= @event.latitude%>
	<%= @event.longitude%>
</p>
<h1><%= @title %></h1>
<p>
  <b>Your Location:</b>
  <% if @relationship.latitude == nil %>
   <b> YOU HAVEN'T BEEN THERE, HAVE YOU??!! </b>
  <% else %>
  <%= @relationship.latitude %>
  <%= @relationship.longitude %>
  <%= @address.distance_to(@b) %>
  <b> Miles </b>
  <% end %>
</p>

<%= link_to "Photos", tasks_path %>