config/routes.rb
Events::Application.routes.draw do

  resources :user_sessions

  resources :users do
    member do
      get :following, :followers
    end
  end

  get "users/new"

  resources :users

  resources :events
  resources :relationships
  
  match '/signup',  :to => 'users#new'
  match '/login',  :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  match '/following', :to => 'users#following'
  
  match '/create',  :to => 'events#new'
  match '/allevents',   :to => 'events#index'
      
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/tasks', :to => 'users#task'
  
  root :to => "pages#home"

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_event_form.html.erb
<%= form_for @event do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_username">
      <%= current_user.username %>
    </span>
    <span class="events">
      <%= pluralize(current_user.events.count, "event") %>
    </span>

  </a>
</div>