config/routes.rb
Events::Application.routes.draw do

  resources :user_sessions

  resources :users do
    member do
      get :following, :followers
    end
  end

  get "users/new"

  resources :users

  resources :events
  resources :relationships
  
  match '/signup',  :to => 'users#new'
  match '/login',  :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  match '/following', :to => 'users#following'
  
  match '/create',  :to => 'events#new'
  match '/allevents',   :to => 'events#index'
      
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/tasks', :to => 'users#task'
  
  root :to => "pages#home"

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  acts_as_mappable :lat_column_name => :latitude,
                   :lng_column_name => :longitude,
                   :auto_geocode => {:field => :street && :city && :state && :zip}
                  
  
  attr_accessible :name, :description, :street, :city, :state, :zip
  
  
  belongs_to :user
  
  validates :name, :presence => true, :length => {:maximum => 40}
  validates :description, :presence => true, :length => {:maximum => 140}
  validates :street, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :zip, :presence => true
  


  
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name  => "Relationship",
                                   :dependent   => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  
  default_scope :order => 'events.created_at DESC'
  
  private
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authorized_user, :only => :destroy
  
  include UserSessionsHelper
  include ApplicationHelper
  include EventsHelper
  include UsersHelper
  
  # GET /events
  # GET /events.xml
  def index
    @title = "All events"
    @events = Event.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @title = "Create"
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = current_user.events.build(params[:event])
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
        format.json  { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
        format.json  { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
      format.json { head :ok }
    end
  end
  
  def followers
    @title = "Followers"
    @event = Event.find(params[:id])
    @events = @event.followers.paginate(:page => params[:page])
    respond_to do |format|
     format.html 
     format.json { render :json => @events}
    end
  end
  
  private 
    def authorized_user
      @event = Event.find(params[:id])
      redirect_to root_path unless current_user?(@event.user)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def gravatar_for_e(event, options = { :size => 50 })
    gravatar_image_tag(event.name.downcase, :alt => event.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/events/_event.html.erb
<tr>
  <table class="events" summary="Events">
	<td class="event">
    <span class="name"><%= link_to event.name, event %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(event.created_at) %> ago.
    </span>
	<% if current_user.following?(event.id) %>
	<td>
		<%= link_to "Task status", {:controller => "users", :action => "task", :id => event.id} %>
	</td>
	<% end %>
  	<% if current_user?(event.user) %>
  	<td>
    	<%= link_to "delete", event,     :method => :delete,
                                     	 :confirm => "You sure?",
                                     	 :title => event.name %>
  	</td>

  	<% end %>

  </table>
</tr>

app/views/events/_follow.html.erb
<%= form_for current_user.relationships.
                          build(:followed_id => @event.id) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/events/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@event) %>
    <%= render 'events/unfollow' %>
  <% else %>
    <%= render 'events/follow' %>
  <% end %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_stats.html.erb
<% @event %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= followers_event_path(@event) %>">
          <span id="followers" class="stat">
            <%= pluralize(@event.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/events/_unfollow.html.erb
<%= form_for @event.reverse_relationships.find_by_followed_id(@event),
             :html => { :method => :delete } do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/events/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="events">
      <%= pluralize(current_user.events.count, "event") %>
    </span>

  </a>

</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>All events</h1>

<%= will_paginate %>

<ul class="events">
  <%= render @events %>
</ul>

<%= will_paginate %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Creator:</b>
  <%= @event.user_id %>
</p>
<p>
  <b>Address:</b>
  <%= @event.street %>
  <%= @event.city %>
  <%= @event.state %>
</p>

<%= render 'follow_form' %>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/show_follow.html.erb
<table summary="Information about followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>
      
      <% unless @events.empty? %>
        <ul class="events">
          <%= render @events %>
        </ul>
        <%= will_paginate @events %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @event.name %><br />
      <strong>URL</strong> <%= link_to event_path(@event), @event %><br />
      <% unless @events.empty? %>
        <% @events.each do |event| %>
          <%= link_to gravatar_for(event.follower, :size => 30), event.follower.name %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>